<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.saga</groupId>
        <artifactId>eventuate-saga-parent</artifactId>
        <version>1.2.0</version>
    </parent>
    <artifactId>saga-common-eventuate</artifactId>
    <dependencies>
        <dependency>
            <groupId>io.eventuate.tram.sagas</groupId>
            <artifactId>eventuate-tram-sagas-spring-orchestration-simple-dsl-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
